name: My First Manual Workflow
on: [workflow_dispatch]
jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - run: make testacc